import fs from "fs";
import path from "path";
import sharp from "sharp";
import {
  validateAllSchemas,
  SCHEMA_REGISTRY,
  LAYOUT_REGISTRY,
} from "../lib/templates/schemas/registry";

const ROOT = path.join(__dirname, "..");
const SOURCES_DIR = path.join(ROOT, "public", "templates", "sources");
const THUMBS_DIR = path.join(ROOT, "public", "templates", "thumbs");
const MANIFEST_PATH = path.join(ROOT, "lib", "templates", "templates.manifest.json");
const CATALOG_OUT = path.join(ROOT, "lib", "templates", "catalog.generated.ts");
const EDITORS_DIR = path.join(ROOT, "app", "editors");

const THUMB_WIDTH = 400;
const DEFAULT_PRICE_TOMAN = 450_000;

type ManifestEntry = {
  name?: string;
  priceToman?: number;
  enabled?: boolean;
  layout?: string;
  schemaId?: string;
  locale?: "ar" | "fa" | "en";
  dir?: "rtl" | "ltr";
};

type Manifest = Record<string, ManifestEntry>;

function slugFromFilename(filename: string): string {
  const base = filename.replace(/\.png$/i, "");
  return base
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function titleFromSlug(slug: string): string {
  return slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function resolveManifestMeta(slug: string, meta: ManifestEntry) {
  const layout = meta.layout ?? "minimalist";
  const schemaId = meta.schemaId ?? "minimalist";
  const locale = meta.locale ?? "en";
  const dir = meta.dir ?? "ltr";

  if (!SCHEMA_REGISTRY[schemaId]) {
    throw new Error(`Unknown schemaId "${schemaId}" for slug "${slug}"`);
  }
  if (!(layout in LAYOUT_REGISTRY)) {
    throw new Error(`Unknown layout "${layout}" for slug "${slug}"`);
  }

  return { layout, schemaId, locale, dir };
}

async function main() {
  validateAllSchemas();

  fs.mkdirSync(SOURCES_DIR, { recursive: true });
  fs.mkdirSync(THUMBS_DIR, { recursive: true });
  fs.mkdirSync(EDITORS_DIR, { recursive: true });

  const manifest: Manifest = fs.existsSync(MANIFEST_PATH)
    ? (JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf8")) as Manifest)
    : {};

  const pngFiles = fs
    .readdirSync(SOURCES_DIR)
    .filter((f) => f.toLowerCase().endsWith(".png"));

  if (pngFiles.length === 0) {
    console.warn("No PNG files in public/templates/sources/");
  }

  const entries: object[] = [];

  for (const file of pngFiles) {
    const slug = slugFromFilename(file);
    const meta = manifest[slug] ?? {};
    if (meta.enabled === false) {
      continue;
    }

    const { layout, schemaId, locale, dir } = resolveManifestMeta(slug, meta);

    const sourcePath = path.join(SOURCES_DIR, file);
    const thumbPath = path.join(THUMBS_DIR, `${slug}.webp`);

    await sharp(sourcePath)
      .resize({ width: THUMB_WIDTH, withoutEnlargement: true })
      .webp({ quality: 80 })
      .toFile(thumbPath);

    entries.push({
      id: slug,
      name: meta.name ?? titleFromSlug(slug),
      thumbnail: `/templates/thumbs/${slug}.webp`,
      sourcePreview: `/templates/sources/${file}`,
      priceToman: meta.priceToman ?? DEFAULT_PRICE_TOMAN,
      editorPath: `/editors/${slug}`,
      schemaId,
      layout,
      locale,
      dir,
    });

    const editorSlugDir = path.join(EDITORS_DIR, slug);
    fs.mkdirSync(editorSlugDir, { recursive: true });
    const pageContent = `import { Suspense } from "react";
import CvTemplateEditorClient from "@/app/minimalist-editor/CvTemplateEditorClient";

export default function EditorPage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-screen flex items-center justify-center text-gray-600">
          Loading editor…
        </div>
      }
    >
      <CvTemplateEditorClient templateId="${slug}" />
    </Suspense>
  );
}
`;
    fs.writeFileSync(path.join(editorSlugDir, "page.tsx"), pageContent, "utf8");
  }

  const catalogSource = `/* eslint-disable */
/** Auto-generated by scripts/sync-templates.ts — do not edit manually */

export type TemplateLocale = "ar" | "fa" | "en";
export type TemplateDir = "rtl" | "ltr";

export interface GeneratedTemplateCatalogEntry {
  id: string;
  name: string;
  thumbnail: string;
  sourcePreview?: string;
  priceToman: number;
  editorPath: string;
  schemaId: string;
  layout: string;
  locale: TemplateLocale;
  dir: TemplateDir;
}

export const GENERATED_TEMPLATE_CATALOG: GeneratedTemplateCatalogEntry[] = ${JSON.stringify(entries, null, 2)};
`;

  fs.writeFileSync(CATALOG_OUT, catalogSource, "utf8");
  console.log(`Synced ${entries.length} template(s).`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
