/* eslint-disable */
/** Auto-generated by scripts/sync-templates.ts — do not edit manually */

export type TemplateLocale = "ar" | "fa" | "en";
export type TemplateDir = "rtl" | "ltr";

export interface GeneratedTemplateCatalogEntry {
  id: string;
  name: string;
  thumbnail: string;
  sourcePreview?: string;
  priceToman: number;
  editorPath: string;
  schemaId: string;
  layout: string;
  locale: TemplateLocale;
  dir: TemplateDir;
}

export const GENERATED_TEMPLATE_CATALOG: GeneratedTemplateCatalogEntry[] = [
  {
    "id": "black-and-white-modern-professional-cv",
    "name": "Black And White Modern Professional Cv",
    "thumbnail": "/templates/thumbs/black-and-white-modern-professional-cv.webp",
    "sourcePreview": "/templates/sources/Black and White Modern Professional CV.png",
    "priceToman": 450000,
    "editorPath": "/editors/black-and-white-modern-professional-cv",
    "schemaId": "minimalist",
    "layout": "minimalist",
    "locale": "en",
    "dir": "ltr"
  },
  {
    "id": "black-and-white-simple-cv-resume",
    "name": "Black And White Simple Cv Resume",
    "thumbnail": "/templates/thumbs/black-and-white-simple-cv-resume.webp",
    "sourcePreview": "/templates/sources/Black and White Simple CV Resume.png",
    "priceToman": 450000,
    "editorPath": "/editors/black-and-white-simple-cv-resume",
    "schemaId": "minimalist",
    "layout": "minimalist",
    "locale": "en",
    "dir": "ltr"
  },
  {
    "id": "blue-modern-professional-resume",
    "name": "Blue Modern Professional Resume",
    "thumbnail": "/templates/thumbs/blue-modern-professional-resume.webp",
    "sourcePreview": "/templates/sources/Blue Modern Professional Resume.png",
    "priceToman": 450000,
    "editorPath": "/editors/blue-modern-professional-resume",
    "schemaId": "minimalist",
    "layout": "minimalist",
    "locale": "en",
    "dir": "ltr"
  },
  {
    "id": "minimalist-cv-resume",
    "name": "Minimalist CV",
    "thumbnail": "/templates/thumbs/minimalist-cv-resume.webp",
    "sourcePreview": "/templates/sources/Minimalist-CV-Resume.png",
    "priceToman": 450000,
    "editorPath": "/editors/minimalist-cv-resume",
    "schemaId": "minimalist",
    "layout": "minimalist",
    "locale": "en",
    "dir": "ltr"
  },
  {
    "id": "test",
    "name": "رزومه عربی",
    "thumbnail": "/templates/thumbs/test.webp",
    "sourcePreview": "/templates/sources/test.png",
    "priceToman": 450000,
    "editorPath": "/editors/test",
    "schemaId": "centeredRtl",
    "layout": "centeredRtl",
    "locale": "ar",
    "dir": "rtl"
  }
];
