import type { Canvas3DElement } from "../../types";
import { CANVAS_HEIGHT_PX } from "../../constants";
import { scaleRect, sx } from "../scale-from-ref";

const NAVY = "#1e2a4a";
const MUTED = "#6b7280";
const BODY = "#374151";
const SIDEBAR_W = 208;
const MAIN_X = 232;
const POPPINS = "poppins";

function r(
  x: number,
  y: number,
  w: number,
  h: number
): { x: number; y: number; width: number; height: number } {
  return scaleRect(x, y, w, h);
}

/** Minimalist CV layout scaled from 595×842 reference to editor A4 px */
export function buildMinimalistCvResumePreset(): Canvas3DElement[] {
  const sidebar = r(0, 0, SIDEBAR_W, 842);
  const photo = r(56, 20, 96, 96);

  return [
    {
      id: "min-sidebar",
      type: "shape",
      ...sidebar,
      height: CANVAS_HEIGHT_PX,
      zIndex: 0,
      fillColor: NAVY,
      borderRadius: 0,
      opacity: 1,
    },
    {
      id: "min-photo",
      type: "image",
      ...photo,
      zIndex: 10,
      src: "",
      shape: "circle",
      objectFit: "cover",
      opacity: 1,
    },
    {
      id: "min-contact-title",
      type: "text",
      ...r(16, 130, 176, 20),
      zIndex: 11,
      variant: "sectionTitle",
      content: "Contact",
      fontId: POPPINS,
      fontSize: sx(11),
      color: "#ffffff",
      fontWeight: "bold",
      align: "left",
    },
    {
      id: "min-contact-phone",
      type: "text",
      ...r(16, 152, 176, 28),
      zIndex: 11,
      variant: "labelValue",
      label: "Phone",
      content: "+1 234 567 890",
      fontId: POPPINS,
      fontSize: sx(9),
      color: "#ffffff",
      fontWeight: "normal",
      align: "left",
      lineHeight: 1.3,
    },
    {
      id: "min-contact-email",
      type: "text",
      ...r(16, 182, 176, 28),
      zIndex: 11,
      variant: "labelValue",
      label: "Email",
      content: "you@email.com",
      fontId: POPPINS,
      fontSize: sx(9),
      color: "#ffffff",
      fontWeight: "normal",
      align: "left",
      lineHeight: 1.3,
    },
    {
      id: "min-contact-address",
      type: "text",
      ...r(16, 212, 176, 36),
      zIndex: 11,
      variant: "labelValue",
      label: "Address",
      content: "City, Country",
      fontId: POPPINS,
      fontSize: sx(9),
      color: "#ffffff",
      fontWeight: "normal",
      align: "left",
      lineHeight: 1.3,
    },
    {
      id: "min-bio-title",
      type: "text",
      ...r(16, 260, 176, 20),
      zIndex: 11,
      variant: "sectionTitle",
      content: "BIO",
      fontId: POPPINS,
      fontSize: sx(11),
      color: "#ffffff",
      fontWeight: "bold",
      align: "left",
    },
    {
      id: "min-bio-birth",
      type: "text",
      ...r(16, 282, 176, 28),
      zIndex: 11,
      variant: "labelValue",
      label: "Birth",
      content: "1990",
      fontId: POPPINS,
      fontSize: sx(9),
      color: "#ffffff",
      fontWeight: "normal",
      align: "left",
      lineHeight: 1.3,
    },
    {
      id: "min-bio-marital",
      type: "text",
      ...r(16, 312, 176, 28),
      zIndex: 11,
      variant: "labelValue",
      label: "Marital status",
      content: "Single",
      fontId: POPPINS,
      fontSize: sx(9),
      color: "#ffffff",
      fontWeight: "normal",
      align: "left",
      lineHeight: 1.3,
    },
    {
      id: "min-expertise-title",
      type: "text",
      ...r(16, 380, 176, 20),
      zIndex: 11,
      variant: "sectionTitle",
      content: "Expertise",
      fontId: POPPINS,
      fontSize: sx(11),
      color: "#ffffff",
      fontWeight: "bold",
      align: "left",
    },
    {
      id: "min-expertise-list",
      type: "text",
      ...r(16, 402, 176, 80),
      zIndex: 11,
      variant: "bulleted",
      content: "",
      fontId: POPPINS,
      fontSize: sx(9),
      color: "#ffffff",
      fontWeight: "normal",
      align: "left",
      lineHeight: 1.5,
      listItems: ["UI/UX Design", "Product strategy", "Frontend development"],
    },
    {
      id: "min-exp-title",
      type: "text",
      ...r(16, 500, 176, 20),
      zIndex: 11,
      variant: "sectionTitle",
      content: "work experience",
      fontId: POPPINS,
      fontSize: sx(11),
      color: "#ffffff",
      fontWeight: "bold",
      align: "left",
    },
    {
      id: "min-exp-logo",
      type: "image",
      ...r(16, 524, 32, 32),
      zIndex: 11,
      src: "",
      shape: "rounded",
      borderRadius: sx(4),
      objectFit: "contain",
      opacity: 1,
    },
    {
      id: "min-exp-company",
      type: "text",
      ...r(52, 522, 140, 36),
      zIndex: 11,
      variant: "simple",
      content: "Company Name\n2020 — Present",
      fontId: POPPINS,
      fontSize: sx(9),
      color: "#ffffff",
      fontWeight: "bold",
      align: "left",
      lineHeight: 1.4,
    },
    {
      id: "min-name",
      type: "text",
      ...r(MAIN_X, 24, 340, 40),
      zIndex: 12,
      variant: "header",
      content: "Your Name",
      fontId: POPPINS,
      fontSize: sx(28),
      color: NAVY,
      fontWeight: "bold",
      align: "left",
      lineHeight: 1.1,
    },
    {
      id: "min-job-title",
      type: "text",
      ...r(MAIN_X, 68, 340, 24),
      zIndex: 12,
      variant: "subtitle",
      content: "Job Title",
      fontId: POPPINS,
      fontSize: sx(11),
      color: MUTED,
      fontWeight: "normal",
      align: "left",
    },
    {
      id: "min-skills-title",
      type: "text",
      ...r(MAIN_X, 110, 340, 24),
      zIndex: 12,
      variant: "sectionTitle",
      content: "Skills",
      fontId: POPPINS,
      fontSize: sx(13),
      color: NAVY,
      fontWeight: "bold",
      align: "left",
    },
    {
      id: "min-skill-cat-title",
      type: "text",
      ...r(MAIN_X, 140, 340, 20),
      zIndex: 12,
      variant: "simple",
      content: "Design",
      fontId: POPPINS,
      fontSize: sx(11),
      color: NAVY,
      fontWeight: "bold",
      align: "left",
    },
    {
      id: "min-skill-divider",
      type: "shape",
      ...r(MAIN_X, 162, 340, 1),
      zIndex: 12,
      fillColor: "#d1d5db",
      opacity: 1,
    },
    {
      id: "min-skill-list",
      type: "text",
      ...r(MAIN_X, 168, 340, 60),
      zIndex: 12,
      variant: "bulleted",
      content: "",
      fontId: POPPINS,
      fontSize: sx(9),
      color: BODY,
      fontWeight: "normal",
      align: "left",
      lineHeight: 1.5,
      listItems: ["Figma", "Adobe XD", "Prototyping"],
    },
    {
      id: "min-projects-title",
      type: "text",
      ...r(MAIN_X, 250, 340, 24),
      zIndex: 12,
      variant: "sectionTitle",
      content: "Projects",
      fontId: POPPINS,
      fontSize: sx(13),
      color: NAVY,
      fontWeight: "bold",
      align: "left",
    },
    {
      id: "min-proj1-title",
      type: "text",
      ...r(MAIN_X, 280, 160, 20),
      zIndex: 12,
      variant: "link",
      content: "Project One",
      href: "https://example.com",
      fontId: POPPINS,
      fontSize: sx(10),
      color: NAVY,
      fontWeight: "bold",
      align: "left",
    },
    {
      id: "min-proj1-desc",
      type: "text",
      ...r(MAIN_X, 302, 160, 72),
      zIndex: 12,
      variant: "simple",
      content: "Short project description highlighting impact and your role.",
      fontId: POPPINS,
      fontSize: sx(9),
      color: BODY,
      fontWeight: "normal",
      align: "left",
      lineHeight: 1.5,
    },
    {
      id: "min-proj2-title",
      type: "text",
      ...r(MAIN_X + 180, 280, 160, 20),
      zIndex: 12,
      variant: "link",
      content: "Project Two",
      href: "https://example.com",
      fontId: POPPINS,
      fontSize: sx(10),
      color: NAVY,
      fontWeight: "bold",
      align: "left",
    },
    {
      id: "min-proj2-desc",
      type: "text",
      ...r(MAIN_X + 180, 302, 160, 72),
      zIndex: 12,
      variant: "simple",
      content: "Another project summary with outcomes and technologies used.",
      fontId: POPPINS,
      fontSize: sx(9),
      color: BODY,
      fontWeight: "normal",
      align: "left",
      lineHeight: 1.5,
    },
  ];
}
